const books = [
  { name: "Genese", slug: "genese", jsx: <span>Gn</span> },
  { name: "Exode", slug: "exode", jsx: <span>Ex</span> },
  { name: "Lévitique", slug: "levitique", jsx: <span>Lv</span> },
  { name: "Nombres", slug: "nombres", jsx: <span>Nb</span> },
  { name: "Deutéronome", slug: "deuteronome", jsx: <span>Dt</span> },
  { name: "Josué", slug: "josue", jsx: <span>Jos</span> },
  { name: "Juges", slug: "juges", jsx: <span>Jg</span> },
  { name: "Ruth", slug: "ruth", jsx: <span>Ru</span> },
  { name: "1 Samuel", slug: "1samuel", jsx: <span>1S</span> },
  { name: "2 Samuel", slug: "2samuel", jsx: <span>2S</span> },
  { name: "1 Rois", slug: "1rois", jsx: <span>1R</span> },
  { name: "2 Rois", slug: "2rois", jsx: <span>2R</span> },
  { name: "1 Chroniques", slug: "1chroniques", jsx: <span>1Ch</span> },
  { name: "2 Chroniques", slug: "2chroniques", jsx: <span>2Ch</span> },
  { name: "Esdras", slug: "esdras", jsx: <span>Esd</span> },
  { name: "Néhémie", slug: "nehemie", jsx: <span>Né</span> },
  { name: "Esther", slug: "esther", jsx: <span>Est</span> },
  { name: "Job", slug: "job", jsx: <span>Jb</span> },
  { name: "Psaumes", slug: "psaumes", jsx: <span>Ps</span> },
  { name: "Proverbes", slug: "proverbes", jsx: <span>Pr</span> },
  { name: "Ecclésiaste", slug: "ecclesiaste", jsx: <span>Ec</span> },
  { name: "Chant de Salomon", slug: "chantdesalomon", jsx: <span>Ct</span> },
  { name: "Isaïe", slug: "isaie", jsx: <span>Is</span> },
  { name: "Lamentations", slug: "lamentations", jsx: <span>Lm</span> },
  { name: "Ezechiel", slug: "ezechiel", jsx: <span>Ez</span> },
  { name: "Daniel", slug: "daniel", jsx: <span>Dn</span> },
  { name: "Osée", slug: "osee", jsx: <span>Os</span> },
  { name: "Joël", slug: "joel", jsx: <span>Os</span> },
  { name: "Amos", slug: "amos", jsx: <span>Am</span> },
  { name: "Abdias", slug: "abdias", jsx: <span>Ab</span> },
  { name: "Jonas", slug: "jonas", jsx: <span>Jon</span> },
  { name: "Michée", slug: "michee", jsx: <span>Mi</span> },
  { name: "Nahum", slug: "nahum", jsx: <span>Na</span> },
  { name: "Habacuc", slug: "habacuc", jsx: <span>Hab</span> },
  { name: "Sophonie", slug: "sophonie", jsx: <span>Sph</span> },
  { name: "Aggée", slug: "aggee", jsx: <span>Ag</span> },
  { name: "Zacharie", slug: "zacharie", jsx: <span>Za</span> },
  { name: "Malachie", slug: "malachie", jsx: <span>Ml</span> },
  { name: "Matthieu", slug: "matthieu", jsx: <span>Mt</span> },
  { name: "Marc", slug: "marc", jsx: <span>Mc</span> },
  { name: "Luc", slug: "luc", jsx: <span>Lc</span> },
  { name: "Jean", slug: "jean", jsx: <span>Jean</span> },
  { name: "Actes", slug: "actes", jsx: <span>Ac</span> },
  { name: "Romains", slug: "romains", jsx: <span>Rm</span> },
  { name: "1 Corinthiens", slug: "1corinthiens", jsx: <span>1Co</span> },
  { name: "2 Corinthiens", slug: "2corinthiens", jsx: <span>2Co</span> },
  { name: "Galates", slug: "galates", jsx: <span>Ga</span> },
  { name: "Ephésiens", slug: "ephesiens", jsx: <span>Eph</span> },
  { name: "Philippiens", slug: "philippiens", jsx: <span>Php</span> },
  { name: "Colossiens", slug: "colossiens", jsx: <span>Col</span> },
  {
    name: "1 Thessaloniciens",
    slug: "1thessaloniciens",
    jsx: <span>1Th</span>,
  },
  {
    name: "2 Thessaloniciens",
    slug: "2thessaloniciens",
    jsx: <span>2Th</span>,
  },
  { name: "1 Timothée", slug: "1timothee", jsx: <span>1Tm</span> },
  { name: "2 Timothée", slug: "2timothee", jsx: <span>2Tm</span> },
  { name: "Tite", slug: "tite", jsx: <span>Tt</span> },
  { name: "Philémon", slug: "philemon", jsx: <span>Phm</span> },
  { name: "Hébreux", slug: "hebreux", jsx: <span>Hé</span> },
  { name: "Jacques", slug: "jacques", jsx: <span>Jc</span> },
  { name: "1 Pierre", slug: "1pierre", jsx: <span>1P</span> },
  { name: "2 Pierre", slug: "2pierre", jsx: <span>2P</span> },
  { name: "1 Jean", slug: "1jean", jsx: <span>1J</span> },
  { name: "2 Jean", slug: "2jean", jsx: <span>2J</span> },
  { name: "3 Jean", slug: "3jean", jsx: <span>3J</span> },
  { name: "Jude", slug: "jude", jsx: <span>Jude</span> },
  { name: "Révélation", slug: "revelation", jsx: <span>Ré</span> },
];

export default books;
